# Generated by Django 6.1.1 on 2026-09-23 17:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArchivoPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='Ejemplo: pdf, png, doc, docx, mp3', max_length=15, unique=True)),
                ('mime_type', models.CharField(help_text='MIME type oficial, ej: application/pdf', max_length=100)),
                ('tamano_maximo_mb', models.PositiveIntegerField(default=50, help_text='Límite máximo permitido en Megabytes')),
            ],
            options={
                'verbose_name': 'Tipo de Archivo Permitido',
                'verbose_name_plural': 'Tipos de Archivos Permitidos',
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('papelera', 'En Papelera'), ('eliminado', 'Eliminado')], default='activo', max_length=20)),
                ('carpeta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='storage.carpeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('extension', models.CharField(db_index=True, max_length=15)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamano_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bucket_minio', models.CharField(max_length=100)),
                ('object_key', models.CharField(db_index=True, help_text='Clave o ruta de localización física del objeto en MinIO', max_length=500, unique=True)),
                ('es_temporal', models.BooleanField(default=False, help_text='Indica si es un archivo con auto-eliminación por TTL (RF-10)')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha y hora límite de vida del archivo temporal', null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('papelera', 'En Papelera'), ('eliminado', 'Eliminado')], default='activo', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to=settings.AUTH_USER_MODEL)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='storage.carpeta')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddConstraint(
            model_name='carpeta',
            constraint=models.UniqueConstraint(fields=('usuario', 'carpeta_padre', 'nombre'), name='unique_carpeta_por_nivel'),
        ),
    ]
