# Generated by Django 6.1.1 on 2026-10-07 06:31

import uuid

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def backfill_trash_metadata(apps, schema_editor):
    Carpeta = apps.get_model("storage", "Carpeta")
    Archivo = apps.get_model("storage", "Archivo")
    database = schema_editor.connection.alias
    folders = Carpeta.objects.using(database)
    files = Archivo.objects.using(database)
    now = timezone.now()
    processed_folder_ids = set()

    roots = folders.filter(estado="papelera").filter(
        Q(carpeta_padre__isnull=True) | ~Q(carpeta_padre__estado="papelera")
    )
    for root_id in roots.values_list("id", flat=True):
        group_id = uuid.uuid4()
        folder_ids = [root_id]
        frontier = [root_id]
        while frontier:
            frontier = list(
                folders.filter(carpeta_padre_id__in=frontier).values_list("id", flat=True)
            )
            folder_ids.extend(frontier)
        folders.filter(id__in=folder_ids).update(
            estado="papelera",
            fecha_papelera=now,
            papelera_grupo=group_id,
        )
        files.filter(carpeta_id__in=folder_ids).update(
            estado="papelera",
            fecha_papelera=now,
            papelera_grupo=group_id,
        )
        processed_folder_ids.update(folder_ids)

    for folder_id in folders.filter(estado="papelera").exclude(
        id__in=processed_folder_ids
    ).values_list("id", flat=True):
        group_id = uuid.uuid4()
        folders.filter(id=folder_id).update(
            fecha_papelera=now,
            papelera_grupo=group_id,
        )
        files.filter(carpeta_id=folder_id).update(
            estado="papelera",
            fecha_papelera=now,
            papelera_grupo=group_id,
        )

    for file_id in files.filter(
        estado="papelera",
        papelera_grupo__isnull=True,
    ).values_list("id", flat=True):
        files.filter(id=file_id).update(
            fecha_papelera=now,
            papelera_grupo=uuid.uuid4(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha_papelera',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='papelera_grupo',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='fecha_papelera',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='papelera_grupo',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_trash_metadata, migrations.RunPython.noop),
    ]
