# Generated by Django 6.1.1 on 2026-10-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
    ]
