# Generated by Django 6.1.1 on 2026-10-10 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_subscription_plan'),
        ('users', '0003_alter_plan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planbenefit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='users.plan'),
        ),
    ]
