# Generated by Django 6.1.1 on 2026-10-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
